# Generated by Django 6.0.3 on 2026-03-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ors', '0002_marksheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marksheet',
            old_name='Chemistry',
            new_name='chemistry',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='Maths',
            new_name='maths',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='Physics',
            new_name='physics',
        ),
        migrations.RenameField(
            model_name='marksheet',
            old_name='RollNo',
            new_name='rollno',
        ),
    ]
