# Generated by Django 6.0.3 on 2026-04-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sos_college',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sos_course',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('collegeId', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
                ('subjectId', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('courseId', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_faculty',
            },
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
            options={
                'db_table': 'sos_marksheet',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_role',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('collegeId', models.IntegerField()),
                ('collegeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_student',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('courseId', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_subject',
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examTime', models.CharField(max_length=40)),
                ('examDate', models.DateField()),
                ('subjectId', models.IntegerField()),
                ('subjectName', models.CharField(max_length=50)),
                ('courseId', models.IntegerField()),
                ('courseName', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_timetable',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('loginId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('mobileNumber', models.CharField(default='', max_length=50)),
                ('roleId', models.IntegerField()),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
    ]
